<<<<<<< HEAD

server.port: 8080

=======
server.port: 8082
>>>>>>> 7595f9b (projeto funcionando e reparado)
spring:
  datasource:
    url: jdbc:postgresql://localhost/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: dev
    password: postgres9961
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace